CREATE TABLE "currency_master" ("id" VARCHAR NOT NULL, "code" varchar(3) NOT NULL, PRIMARY KEY ("id"));
CREATE TABLE "transaction_type_master" ("type" VARCHAR NOT NULL, PRIMARY KEY ("type"));
CREATE TABLE "users" ("id" VARCHAR NOT NULL, "name" varchar(20) NOT NULL, "email" VARCHAR NOT NULL, PRIMARY KEY ("id"));
CREATE TABLE "accounts" ("id" VARCHAR NOT NULL, "user_id" VARCHAR NOT NULL, "name" varchar(10), "password_hash" VARCHAR NOT NULL, "balance" float8 NOT NULL, "currency_id" VARCHAR NOT NULL, "last_updated_at" TIMESTAMPTZ NOT NULL, PRIMARY KEY ("id"));
CREATE TABLE "transactions" ("id" VARCHAR NOT NULL, "account_id" VARCHAR NOT NULL, "receiver_account_id" VARCHAR, "type" varchar(20) NOT NULL, "amount" float8 NOT NULL, "currency_id" VARCHAR NOT NULL, "transaction_at" TIMESTAMPTZ NOT NULL, PRIMARY KEY ("id"));
CREATE TABLE "authentications" ("id" VARCHAR NOT NULL, "user_id" VARCHAR NOT NULL, "password_hash" VARCHAR NOT NULL, PRIMARY KEY ("id"), UNIQUE ("user_id"));
CREATE UNIQUE INDEX "account_user_id_idx" ON "accounts" ("user_id");
CREATE UNIQUE INDEX "user_email_idx" ON "users" ("email");
CREATE UNIQUE INDEX "authentication_user_id_idx" ON "authentications" ("user_id");
CREATE INDEX "transaction_account_id_idx" ON "transactions" ("account_id");
CREATE INDEX "transaction_receiver_account_id_idx" ON "transactions" ("receiver_account_id");
ALTER TABLE accounts ADD CONSTRAINT fk_account_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE accounts ADD CONSTRAINT fk_account_currency_id FOREIGN KEY (currency_id) REFERENCES currency_master(id) ON DELETE CASCADE;
ALTER TABLE authentications ADD CONSTRAINT fk_auth_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE transactions ADD CONSTRAINT fk_transaction_account_id FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;
ALTER TABLE transactions ADD CONSTRAINT fk_transaction_receiver_account_id FOREIGN KEY (receiver_account_id) REFERENCES accounts(id) ON DELETE CASCADE;
ALTER TABLE transactions ADD CONSTRAINT fk_transaction_currency_id FOREIGN KEY (currency_id) REFERENCES currency_master(id) ON DELETE CASCADE;
ALTER TABLE transactions ADD CONSTRAINT fk_transaction_type FOREIGN KEY (type) REFERENCES transaction_type_master(type) ON DELETE CASCADE;
