version: '3.8'
services:
  postgres:
    container_name: POCGO_DB
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: POCGO_LOCAL_DB
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'Asia/Tokyo'
    networks:
      - default
