// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/account/create_account_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	account "github.com/u104rak1/pocgo/internal/application/account"
)

// MockICreateAccountUsecase is a mock of ICreateAccountUsecase interface.
type MockICreateAccountUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockICreateAccountUsecaseMockRecorder
}

// MockICreateAccountUsecaseMockRecorder is the mock recorder for MockICreateAccountUsecase.
type MockICreateAccountUsecaseMockRecorder struct {
	mock *MockICreateAccountUsecase
}

// NewMockICreateAccountUsecase creates a new mock instance.
func NewMockICreateAccountUsecase(ctrl *gomock.Controller) *MockICreateAccountUsecase {
	mock := &MockICreateAccountUsecase{ctrl: ctrl}
	mock.recorder = &MockICreateAccountUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreateAccountUsecase) EXPECT() *MockICreateAccountUsecaseMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockICreateAccountUsecase) Run(ctx context.Context, cmd account.CreateAccountCommand) (*account.CreateAccountDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, cmd)
	ret0, _ := ret[0].(*account.CreateAccountDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockICreateAccountUsecaseMockRecorder) Run(ctx, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockICreateAccountUsecase)(nil).Run), ctx, cmd)
}
