// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/user/create_user_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	user "github.com/ucho456job/pocgo/internal/application/user"
)

// MockICreateUserUsecase is a mock of ICreateUserUsecase interface.
type MockICreateUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockICreateUserUsecaseMockRecorder
}

// MockICreateUserUsecaseMockRecorder is the mock recorder for MockICreateUserUsecase.
type MockICreateUserUsecaseMockRecorder struct {
	mock *MockICreateUserUsecase
}

// NewMockICreateUserUsecase creates a new mock instance.
func NewMockICreateUserUsecase(ctrl *gomock.Controller) *MockICreateUserUsecase {
	mock := &MockICreateUserUsecase{ctrl: ctrl}
	mock.recorder = &MockICreateUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreateUserUsecase) EXPECT() *MockICreateUserUsecaseMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockICreateUserUsecase) Run(ctx context.Context, cmd user.CreateUserCommand) (*user.CreateUserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, cmd)
	ret0, _ := ret[0].(*user.CreateUserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockICreateUserUsecaseMockRecorder) Run(ctx, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockICreateUserUsecase)(nil).Run), ctx, cmd)
}
