// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/user/read_user_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	user "github.com/ucho456job/pocgo/internal/application/user"
)

// MockIReadUserUsecase is a mock of IReadUserUsecase interface.
type MockIReadUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIReadUserUsecaseMockRecorder
}

// MockIReadUserUsecaseMockRecorder is the mock recorder for MockIReadUserUsecase.
type MockIReadUserUsecaseMockRecorder struct {
	mock *MockIReadUserUsecase
}

// NewMockIReadUserUsecase creates a new mock instance.
func NewMockIReadUserUsecase(ctrl *gomock.Controller) *MockIReadUserUsecase {
	mock := &MockIReadUserUsecase{ctrl: ctrl}
	mock.recorder = &MockIReadUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReadUserUsecase) EXPECT() *MockIReadUserUsecaseMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIReadUserUsecase) Run(ctx context.Context, cmd user.ReadUserCommand) (*user.ReadUserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, cmd)
	ret0, _ := ret[0].(*user.ReadUserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIReadUserUsecaseMockRecorder) Run(ctx, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIReadUserUsecase)(nil).Run), ctx, cmd)
}
