// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みのユーザーのプロフィールを返します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User API"
                ],
                "summary": "プロフィールの取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/me.ReadMyProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/me/accounts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しい口座を作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account API"
                ],
                "summary": "口座の作成",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.CreateAccountRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/accounts.CreateAccountResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Failed or Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ValidationProblemDetail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/me/accounts/{account_id}/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定された口座の取引履歴を取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction API"
                ],
                "summary": "取引一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "操作する口座ID",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "取引日の開始日（YYYYMMDD）",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "取引日の終了日（YYYYMMDD）",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "取引種別（DEPOSIT, WITHDRAW, TRANSFER カンマ区切りで複数指定可）",
                        "name": "operationTypes",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ソート順（ASC, DESC）",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ページサイズ（1~100）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ページ番号（1~）",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transactions.ListTransactionsResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Failed or Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ValidationProblemDetail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "This endpoint executes a transaction (deposit, withdraw, or transfer) for the specified account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction API"
                ],
                "summary": "Execute Transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID to be operated.",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transactions.ExecuteTransactionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transactions.ExecuteTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Failed or Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ValidationProblemDetail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/signin": {
            "post": {
                "description": "ユーザーのメールアドレスとパスワードを使用してユーザーを認証し、アクセストークンを発行します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication API"
                ],
                "summary": "サインイン",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/signin.SigninRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/signin.SigninResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Failed or Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ValidationProblemDetail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/signup": {
            "post": {
                "description": "新しいユーザーを作成し、アクセストークンを発行します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication API"
                ],
                "summary": "サインアップ",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/signup.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/signup.SignupResponse"
                        }
                    },
                    "400": {
                        "description": "Validation Failed or Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ValidationProblemDetail"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ProblemDetail"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "accounts.CreateAccountRequestBody": {
            "type": "object",
            "properties": {
                "currency": {
                    "description": "通貨（JPY または USD）",
                    "type": "string",
                    "example": "JPY"
                },
                "name": {
                    "description": "3 ～ 20 文字のアカウント名",
                    "type": "string",
                    "example": "For work"
                },
                "password": {
                    "description": "4 桁のパスワード",
                    "type": "string",
                    "example": "1234"
                }
            }
        },
        "accounts.CreateAccountResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "口座残高",
                    "type": "number",
                    "example": 0
                },
                "currency": {
                    "description": "通貨",
                    "type": "string",
                    "example": "JPY"
                },
                "id": {
                    "description": "口座ID",
                    "type": "string",
                    "example": "01J9R7YPV1FH1V0PPKVSB5C7LE"
                },
                "name": {
                    "description": "口座名",
                    "type": "string",
                    "example": "For work"
                },
                "updatedAt": {
                    "description": "口座の更新日時",
                    "type": "string",
                    "example": "2021-08-01T00:00:00Z"
                }
            }
        },
        "me.ReadMyProfileResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "ユーザーのメールアドレス",
                    "type": "string",
                    "example": "sato@example.com"
                },
                "id": {
                    "description": "ユーザーのID",
                    "type": "string",
                    "example": "01J9R7YPV1FH1V0PPKVSB5C8FW"
                },
                "name": {
                    "description": "ユーザーの名前",
                    "type": "string",
                    "example": "Sato Taro"
                }
            }
        },
        "response.ProblemDetail": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Error detail message"
                },
                "instance": {
                    "type": "string",
                    "example": "/path/to/resource"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                },
                "title": {
                    "type": "string",
                    "example": "Error title"
                },
                "type": {
                    "type": "string",
                    "example": "https://example.com/probs/error-title"
                }
            }
        },
        "response.ValidationError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "field name"
                },
                "message": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "response.ValidationProblemDetail": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Error detail message"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ValidationError"
                    }
                },
                "instance": {
                    "type": "string",
                    "example": "/path/to/resource"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                },
                "title": {
                    "type": "string",
                    "example": "Error title"
                },
                "type": {
                    "type": "string",
                    "example": "https://example.com/probs/error-title"
                }
            }
        },
        "signin.SigninRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "ログイン用メールアドレス",
                    "type": "string",
                    "example": "sato@example.com"
                },
                "password": {
                    "description": "ログイン用パスワード",
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "signin.SigninResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "description": "アクセストークン",
                    "type": "string",
                    "example": "eyJhb..."
                }
            }
        },
        "signup.SignupRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "ログイン用メールアドレス",
                    "type": "string",
                    "example": "sato@example.com"
                },
                "name": {
                    "description": "3 ～ 20 文字のユーザー名",
                    "type": "string",
                    "example": "Sato Taro"
                },
                "password": {
                    "description": "8 ～ 20 文字のログイン用パスワード",
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "signup.SignupResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "description": "アクセストークン",
                    "type": "string",
                    "example": "eyJhb..."
                },
                "user": {
                    "description": "ユーザー",
                    "allOf": [
                        {
                            "$ref": "#/definitions/signup.SignupResponseBodyUser"
                        }
                    ]
                }
            }
        },
        "signup.SignupResponseBodyUser": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "ユーザーのメールアドレス",
                    "type": "string",
                    "example": "sato@example.com"
                },
                "id": {
                    "description": "ユーザーID",
                    "type": "string",
                    "example": "01J9R7YPV1FH1V0PPKVSB5C8FW"
                },
                "name": {
                    "description": "ユーザー名",
                    "type": "string",
                    "example": "Sato Taro"
                }
            }
        },
        "transactions.ExecuteTransactionRequestBody": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "The transaction amount.",
                    "type": "number",
                    "example": 1000
                },
                "currency": {
                    "description": "The currency of the transaction. Supported values are JPY and USD.",
                    "type": "string",
                    "example": "JPY"
                },
                "operationType": {
                    "description": "Specifies the type of transaction. Valid values are DEPOSIT, WITHDRAWAL, or TRANSFER.",
                    "type": "string",
                    "example": "DEPOSIT"
                },
                "password": {
                    "description": "The account password.",
                    "type": "string",
                    "example": "1234"
                },
                "receiverAccountId": {
                    "description": "Required for TRANSFER operations. Represents the recipient account ID.",
                    "type": "string",
                    "example": "01J9R8AJ1Q2YDH1X9836GS9D87"
                }
            }
        },
        "transactions.ExecuteTransactionResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string",
                    "example": "01J9R7YPV1FH1V0PPKVSB5C8FW"
                },
                "amount": {
                    "type": "number",
                    "example": 1000
                },
                "currency": {
                    "type": "string",
                    "example": "JPY"
                },
                "id": {
                    "type": "string",
                    "example": "01J9R8AJ1Q2YDH1X9836GS9E89"
                },
                "operationType": {
                    "type": "string",
                    "example": "DEPOSIT"
                },
                "receiverAccountId": {
                    "type": "string",
                    "example": "01J9R8AJ1Q2YDH1X9836GS9D87"
                },
                "transactionAt": {
                    "type": "string",
                    "example": "2024-03-20T15:00:00Z"
                }
            }
        },
        "transactions.ListTransactionsResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "description": "取引件数",
                    "type": "integer",
                    "example": 1
                },
                "transactions": {
                    "description": "取引一覧",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transactions.ListTransactionsTransaction"
                    }
                }
            }
        },
        "transactions.ListTransactionsTransaction": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "口座ID",
                    "type": "string",
                    "example": "01J9R7YPV1FH1V0PPKVSB5C8FW"
                },
                "amount": {
                    "description": "取引金額",
                    "type": "number",
                    "example": 1000
                },
                "currency": {
                    "description": "通貨",
                    "type": "string",
                    "example": "JPY"
                },
                "id": {
                    "description": "取引ID",
                    "type": "string",
                    "example": "01J9R8AJ1Q2YDH1X9836GS9E89"
                },
                "operationType": {
                    "description": "取引種別",
                    "type": "string",
                    "example": "DEPOSIT"
                },
                "receiverAccountId": {
                    "description": "受取口座ID",
                    "type": "string",
                    "example": "01J9R8AJ1Q2YDH1X9836GS9D87"
                },
                "transactionAt": {
                    "description": "取引日時",
                    "type": "string",
                    "example": "2024-03-20T15:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "pocgo API",
	Description:      "This is a sample server. <br />Please enter your token in the format: \"Bearer <token>\" in the Authorization header.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
