definitions:
  response.ErrorResponse:
    properties:
      code:
        example: ErrorCode
        type: string
      message:
        example: error message
        type: string
    type: object
  response.ValidationError:
    properties:
      field:
        example: field name
        type: string
      message:
        example: error message
        type: string
    type: object
  response.ValidationErrorResponse:
    properties:
      code:
        example: ErrorCode
        type: string
      errors:
        items:
          $ref: '#/definitions/response.ValidationError'
        type: array
    type: object
  signup.SignupRequestBody:
    properties:
      user:
        $ref: '#/definitions/signup.SignupRequestBodyUser'
    type: object
  signup.SignupRequestBodyAccount:
    properties:
      currency:
        example: JPY
        type: string
      name:
        example: For work
        type: string
      password:
        example: "1234"
        type: string
    type: object
  signup.SignupRequestBodyUser:
    properties:
      account:
        $ref: '#/definitions/signup.SignupRequestBodyAccount'
      email:
        example: sato@example.com
        type: string
      name:
        example: Sato Taro
        type: string
      password:
        example: password
        type: string
    type: object
  signup.SignupResponseBody:
    properties:
      accessToken:
        example: eyJhb...
        type: string
      user:
        $ref: '#/definitions/signup.SignupResponseBodyUser'
    type: object
  signup.SignupResponseBodyAccount:
    properties:
      balance:
        example: 0
        type: number
      currency:
        example: JPY
        type: string
      id:
        example: 01J9R7YPV1FH1V0PPKVSB5C7LE
        type: string
      name:
        example: For work
        type: string
      updatedAt:
        example: "2021-08-01T00:00:00Z"
        type: string
    type: object
  signup.SignupResponseBodyUser:
    properties:
      account:
        $ref: '#/definitions/signup.SignupResponseBodyAccount'
      email:
        example: sato@example.com
        type: string
      id:
        example: 01J9R7YPV1FH1V0PPKVSB5C8FW
        type: string
      name:
        example: Sato Taro
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server.
  title: Pocgo API
  version: "1.0"
paths:
  /v1/signup:
    post:
      consumes:
      - application/json
      description: Signup
      parameters:
      - description: SignupRequestBody
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/signup.SignupRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/signup.SignupResponseBody'
        "400":
          description: Validation Failed or Bad Request
          schema:
            $ref: '#/definitions/response.ValidationErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Signup
      tags:
      - Authentication
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
