name: Integration Test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: localhost
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Install Atlas
        run: |
          curl -sSfL https://atlasgo.sh | sh
          echo 'export PATH=$PATH:$HOME/.atlas/bin' >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      - name: Start PostgreSQL Container
        run: |
          docker compose -f ./docker/docker-compose.yml up -d postgres
          sleep 5s
      - name: Run Migrations
        run: go run ./cmd/postgres/main.go migrate refresh
      - name: Run Integration Tests
        run: go test -v ./test/integration
