name: Integration Test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      - name: Run Integration Tests
        run: make integration_test 
