name: Integration Test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Install Atlas
        run: |
          curl -sSfL https://atlasgo.sh | sh
          echo 'export PATH=$PATH:$HOME/.atlas/bin' >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      - name: Start Dependencies
        run: make start_dependencies_for_integration_test_in_ci
      - name: Run Integration Tests
        run: make integration_test_host
