name: Vulnerability Check
on:
  schedule:
    - cron: '0 23 * * *' # Runs every day at 8:00 (jst)
jobs:
  go_vulncheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.23.1
          work-dir: ./
          go-package: ./...

